"""empty message

Revision ID: 3bb9502e374b
Revises: None
Create Date: 2015-01-06 15:22:18.781749

"""

# revision identifiers, used by Alembic.
revision = '3bb9502e374b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('riparazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cognome', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('indirizzo', sa.String(length=80), nullable=True),
    sa.Column('citta', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=80), nullable=True),
    sa.Column('cell', sa.String(length=80), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('oggetto', sa.String(length=80), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('referenza', sa.String(length=80), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('data_arrivo', sa.DateTime(), nullable=True),
    sa.Column('consegna_prevista', sa.DateTime(), nullable=True),
    sa.Column('difetto', sa.Text(), nullable=False),
    sa.Column('riparatore', sa.String(length=80), nullable=True),
    sa.Column('n_riparazione', sa.String(length=80), nullable=True),
    sa.Column('preventivo', sa.Float(), nullable=True),
    sa.Column('riparazione_effettuata', sa.Text(), nullable=True),
    sa.Column('data_riparazione', sa.DateTime(), nullable=True),
    sa.Column('garanzia', sa.String(length=80), nullable=True),
    sa.Column('costo_riparazione', sa.Float(), nullable=True),
    sa.Column('spese_spedizione', sa.Float(), nullable=True),
    sa.Column('totale', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('finito', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('riparazioni')
    op.drop_table('users')
    op.drop_table('categorie')
    ### end Alembic commands ###
